# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  push:
    branches: [ live ]
  schedule:
    # Run at 0815 daily
    - cron: '0 6 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.DAILY_BUILD_HOOK }}